In [57]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [58]:
cars =  pd.read_csv("cleaned_data.csv")
cars.head()

Name         style    Exterior color     interior color  \
0    Titan  Pickup Truck   Deep Blue Pearl              Black   
1    Civic     Hatchback  Sonic Gray Pearl            Unknown   
2  Charger         Sedan       Indigo Blue  Brazen Gold/Black   
3    F-150  Pickup Truck      Shadow Black  Medium Earth Gray   
4   Altima         Sedan             White              Black   

                      Engine drive type Fuel Type Transmission  Mileage  \
0                    V-8 Gas        4WD       Gas    Automatic    82230   
1  Inline-4 Gas Turbocharged        FWD       Gas    Automatic    24282   
2                    V-8 Gas        RWD       Gas    Automatic    19468   
3       V-6 Gas Turbocharged        4WD       Gas    Automatic   195205   
4               Inline-4 Gas        FWD       Gas    Automatic    92366   

   mpg city  mpg highway  price  Year  Engine V   Brand  
0        15           21  35620  2018       5.6  Nissan  
1        31           40  24999  2020       1.5   Honda  
2        16           25  41999  2018       5.7   Dodge  
3        18           23  20995  2018       2.7    Ford  
4        27           38  10995  2015       2.5  Nissan

In [59]:
cars.columns

Index(['Name', 'style', 'Exterior color', 'interior color', 'Engine',
       'drive type', 'Fuel Type', 'Transmission', 'Mileage', 'mpg city',
       'mpg highway', 'price', 'Year', 'Engine V', 'Brand'],
      dtype='object')

In [68]:
X =  cars[['Name', 'style', 'Exterior color', 'interior color', 'Engine',
       'drive type', 'Fuel Type', 'Transmission', 'Mileage', 'mpg city',
       'mpg highway', 'Year', 'Engine V', 'Brand']]


Y = cars["price"].values

In [69]:
from sklearn.preprocessing import OneHotEncoder

onehot = OneHotEncoder(categories="auto", handle_unknown="ignore")

categorical_features = onehot.fit_transform(X.iloc[:, [1,4,5,6,7,13]]).toarray()
print(categorical_features)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [70]:
print(categorical_features.shape)

(6532, 91)


In [71]:
X = np.delete(X.values, [0,1,2,3,4,5,6,7,13], 1)
print(X.shape)

In [73]:
X = np.concatenate((X,categorical_features), axis=1)

In [74]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    X, Y,
    test_size=0.1,
    random_state=42
)

In [75]:
from sklearn.preprocessing import StandardScaler

std_scaler = StandardScaler()
std_scaler.fit(x_train)

x_train_std = std_scaler.transform(x_train)
x_test_std  = std_scaler.transform(x_test)

In [76]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression(fit_intercept=True, normalize="deprecated")
lr.fit(x_train_std, y_train)

print(lr.score(x_test_std, y_test))

0.8562694401582878


In [78]:
from sklearn.pipeline import make_pipeline

pip_lr = make_pipeline(
    StandardScaler(),
    LinearRegression(fit_intercept=True, normalize="deprecated")
)
pip_lr.fit(x_train, y_train)
h_pred = pip_lr.predict(x_test)
print(f"Test Accuracy : {pip_lr.score(x_test, y_test)}")

Test Accuracy : 0.8562694401582878
